"""Initial migration

Revision ID: 4254e1ca740d
Revises: 
Create Date: 2024-11-17 16:00:18.967079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4254e1ca740d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dormitory_id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dormitory_id'], ['dormitories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rooms', sa.Column('floor_id', sa.Integer(), nullable=False))
    op.drop_constraint('rooms_ibfk_1', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'floors', ['floor_id'], ['id'])
    op.drop_column('rooms', 'dormitory_id')
    op.add_column('students', sa.Column('grup', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'grup')
    op.add_column('rooms', sa.Column('dormitory_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_ibfk_1', 'rooms', 'dormitories', ['dormitory_id'], ['id'])
    op.drop_column('rooms', 'floor_id')
    op.drop_table('floors')
    # ### end Alembic commands ###
